//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionair
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_PartOne
    {
        public System.Guid RefID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Status { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsMedicalExamination { get; set; }
        public string BloodTest { get; set; }
        public string Urinalysis { get; set; }
        public string BloodPressure { get; set; }
        public string BreastExamination { get; set; }
        public string CervicalCancer { get; set; }
        public string ECG { get; set; }
        public string TomographyLung { get; set; }
        public string OtherExam { get; set; }
        public Nullable<bool> IsCongenitalDisease { get; set; }
        public string Health { get; set; }
    }
}
